language: android
jdk: oraclejdk8

env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)

android:
  components:
     - tools
     - build-tools-26.0.2
     - platform-tools
     - extra-android-m2repository
     - extra-google-android-support
     - android-26

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew checkstyle assemble testDebug